// export const HOST = import.meta.env.VITE_SERVER_URL;
export const HOST ="http://localhost:8747"
export const AUTH_ROUTES = "api/auth";
export const SIGNUP_ROUTE = `${AUTH_ROUTES}/signup`;
export const LOGIN_ROUTE = `${AUTH_ROUTES}/login`;
export const ADD_PROFILE_IMAGE = `${AUTH_ROUTES}/add-profile-image`;
export const GET_USER_INFO =  `${AUTH_ROUTES}/getuserinfo`;
export const UPDATE_PROFILE =  `${AUTH_ROUTES}/updateprofile`;
export const UPDATE_PROFILE_IMAGE =  `${AUTH_ROUTES}/updateprofileimage`;
export const PASS_ISSUE_ROUTE = `${AUTH_ROUTES}/issuepass`;
export const GET_STUDENT_DATA_ROUTE = `${AUTH_ROUTES}/getstudentdata`;
export const FACE_VERIFICATION_ROUTE = `${AUTH_ROUTES}/face-verify`;